### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by ghost** [dariatrainor/MobilogicsBinding#1]
Hi, thanks for doing this binding. I am trying to run the sample and I get "The namespace 'MobilogicBinding' already contains a definition for Command' and about 7 more errors like this. It also errors on 'unsafe' code even if I have AllowUnsafeBlocks = true. Can you help me figure this out?

Much appreciate it

Derek

**Comment by dariatrainor** [comment]
Hello,

Sure. I can help you with it.

Have you got a mobilogic library installed? It is not included in my github
project (you have to buy the device and ask mobilogic to supply you with
the library).

Regards,
Daria.

**Comment by ghost** [comment]
Hey,

Thanks for the help. Yes I have the SDK from Mobilogics and I have your binding and the sample. I added MobilogicsCore and Barcode in the same folder as the MobilogicsCore.linkwith.cs and the Barcode.linkwith.cs for the binding project. That compiles with no errors. But when I do the same for the sample I get errors. I guess the questions is what do i have to do to get the sample working. What are the steps? Once I get the sample working then I can use the binding and the example code. 

I appreciate your help and your work on this binding!!

Derek

**Comment by dariatrainor** [comment]
Hello,

You have got to link the binding project and the sample project. 
Try following instructions here - http://developer.xamarin.com/guides/cross-platform/application_fundamentals/shared_projects/

And let me know if it still does not compile.
